### ISSUE TITLE
Create action does not check if nickname is already used.

### ISSUE THREAD

**Issue by Thykof** [massalabs/thyra-plugin-wallet#123]
**Describe the bug**
*A clear and concise description of what the bug is.*

If you create an account with a nickname of an account that already exists, it will erase the current one.

**To Reproduce**

1. Run the wallet in standalone: `STANDALONE=1 wails dev` (on macos and linux)
3. create a wallet: `curl --location --request POST 'http://127.0.0.1:8080/api/accounts/created'`
4. create another wallet with same nickname: same as above

**Expected behavior**
*A clear and concise description of what you expected to happen.*

TBD: it should return an error 400 nickname already exists.

**Additional context**
*Add any other context about the problem here.*

For import, the rule already exists. This issue only concerns generating a new random account.

**Comment by SlnPons** [comment]
@Thykof some questions and comments: 
1. if some sections of the template aren't appropriate, just remove them to simplify the lecture. (here: thyra version / desktop / additional content / screenshots....) You need to make sure it's easy to read so we catch important info ;)
2. is this a bug or a task?
3. this is related to the top priority for the wallet so this point must be shared on appropriate channel and discussed with PM asap to define expected behaviour! Don't hesitate to ping me on this any time
4. this rule used to exist on thyra wallet. Did we remove the rules and error messages while cleaning the code?
5. There are multiple use cases to handle, and we must prioritise them as we won't address them all.
* Import vs Create
* and diff use cases inside each

Let me know if I understood correctly this ticket so I can remove ambiguiti and do it.

**Comment by Thykof** [comment]
@SlnPons I have update the issue description.

**Comment by SlnPons** [comment]
After discussing with Nathan, I finally understood that this ticket relates to the back-end rules. Atm all the product rules are only existing on the front-end; and it is about replicated them in the back-end.
Currently we have 2 types of rules, let's call them:
* Basic: preventing users from erasing things or doing wrong actions
eg: can't create an account with the same nickname, can't import an account with the same nickname and / or private key etc.... 

* Errors: letting users know when something went wrong and why 
eg: wrong password, deletion failed because ..., No special characters enabled etc.... 

Should we create all these rules in front-end and back-end? Only some of them?
What do you think @Thykof @peterjah? 
What is the standard way of doing @gregLibert?

**Comment by Thykof** [comment]
the guideline is: nether trust user inputs. it's always better to do the checks both in front and back. In addition, there are two user input entry point: front and API: so we need to enforce the rules both side IMO

**Comment by Thykof** [comment]
solved by https://github.com/massalabs/thyra-plugin-wallet/pull/231

**Comment by SlnPons** [comment]
Niceeeee! :)
