### ISSUE TITLE
Update thyra-plugin-wallet

### ISSUE THREAD

**Issue by B-Naoufal** [massalabs/thyra-plugin-wallet#4]
**Describe the bug**
Some Functionalities are missing from the wallet plugin version : Import New wallet, encoding of private key.
==> We need to have the same functionalities when we use the wallet plugin version.

**Comment by SlnPons** [comment]
Hey @B-Naoufal I see that there is a PR linked to this issue. But I was under the impression that we'll let this out to improve these features while adding them to the wallet. 
* Import new wallet from the client = make sure that the massa-client wallet & thyra wallet have the same format so we can import any wallet. 
* encoding private key = same make sure we're using the same algo for massa-client and thyra wallets. 

Did you understand the same thing? 
Don't hesitate to ping me to discuss if better :)

**Comment by B-Naoufal** [comment]
@SlnPons  this PR is in StandBy Now Since the focus is more on connecting the first version of wallet as Plug-in to thyra.

**Comment by SlnPons** [comment]
Yeah in any case this ticket is not enough specific. We should list explicitly the features that need to be added so that we can evaluate if we really want to add them to wallet plug-in or not.
Typically, I was under the impression than the import wallet function in thyra wallet wasn't scalable and so should be changed to be added to wallet plug-in... 

@B-Naoufal did you start to code anything? Trying to understand how to not through away your work but still making sure it was the right thing ;)

**Comment by SlnPons** [comment]
Closing this task as I created this one to handle things pointed out in the description with more details: https://github.com/massalabs/thyra-plugin-wallet/issues/18
