### ISSUE TITLE
CORS origin allow all for Dapp tests

### ISSUE THREAD

**Issue by SebastienValla** [massalabs/thyra-plugin-wallet#46]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Thyra version**
The version of Thyra the bug is present in.

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS, Windows...]

**Additional context**

**Comment by Thykof** [comment]
@SlnPons for QA review: launch the token factory, if it works as expected then this issue is OK

**Comment by SlnPons** [comment]
I can't launch the token factory atm because the issue is not merged and I would like to test this from a user perspective. 
That is said, I had this problem with the wallet plugin. And still has it - see below


![Image](https://user-images.githubusercontent.com/109611779/227591329-8e6a2d29-1982-4e88-b548-edd0251e7341.png)


Here is what I did: 
1. Made a new release of the wallet plugin
2. Git pull + go run thyra main
3. Installed the new version of the plugin (using the zip URL) 
4. Open the wallet page 
5. See error in the console
6. Try to create a wallet: same error message


![Image](https://user-images.githubusercontent.com/109611779/227593211-81374b27-baa5-4d16-9c85-bb92bbe3b84d.png)

**Comment by SlnPons** [comment]
@Thykof after investigating on the problem I had; it seems that it's due to the release. 
How did I find this? 
* When I launch thyra, the plugin manager gives me a port to which I can reach the wallet plugin. If I go to this port, it works.
* When I installed the wallet plugin using the front-end and the latest release (where the CORS changes are merged - see v0.0.2) it doesn't work and I see the errors described in the comments above.

**Comment by SlnPons** [comment]
Alright so after investigating with multiple devs. The problem is still here but it's not 100% sure that it is related to CORS. 
However, I'll keep the discussion here as I don't know what this CORS change is suppose to do (the issue is basically empty....) and the QA review suggested process indicates that I should be able to use a plugin normally. It is not the case.

My problem is linked to the fact that I have a `contenu mixte actif` error that prevent me from using correctly some plugins. 
ATM, I experience the same problem on the wallet plugin & blog no-code plugins (note that I can't use the factories as it's running on the specific branch where wallet is on port 8080 so I don't use them as exemples)


On the wallet plugin,

1. Install the wallet plugin using front-end
2. Click on "open"
3. (using macos + firefox) it opens https://my.massa/thyra/* (fyi- the URL of the plugin manager is not compliant with the naming convention + there is a space in it 😭) 
4. I see the error above.
--> the api call is made on http://my.massa/thyra/.... /rest/wallet: so when accessing the page in https://my.massa/** this error occurs and prevent me from using the wallet correctly. 
--> if I change the url to http: firefox is preventing it and so the wallet it still not working. 
--> if I change browser and use googlechrome, same problem as above with https but if I use http, the problem is solved.

Conclusion: there is problem as the expected behaviour is for the links to open in https (web2 standard: to match for the mainnet) and for our products to work (in http AND https)


On the blog no-code plugin, 
1. install the plugin
2. click on "open"
3. (using macos + firefox) it opens https://my.massa/thyra/*
4. I can use the plugin normally
5. when I click on "finish", I see the pop-up to push my website on chain 
6. I can't see the list of wallet that I have
Nb: this plugin is using the thyra wallet and not the wallet plugin. 
--> the api call is the same as above http...... which prevent the list of wallet from being listed.
--> same as above, firefox can't change to http vs. googlechrome can change and so it works. 

Conclusion: it seems that we have problem with the plugin manager API as it's not localise in on the wallet plugin. 
We must solve this. 

Do you have an idea of how we can do that please? 
cc @peterjah or @gregLibert
